# basic Numpy Reference

In [2]:
# 버전 확인 : conda python 3.9.12 환경에서 실행함
import sys
sys.version

'3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]'

### Python List

#### 인덱싱 indexing

In [3]:
# 인덱싱 indexing
a = [1,2,3,4,5,6]
print(a)
print(f'a[0]:{a[0]} \na[1]:{a[1]} \na[2]:{a[2]} \na[3]:{a[3]} \na[4]:{a[4]} \na[5]:{a[5]} \na[-1]:{a[-1]} \na[-2]:{a[-2]} \na[True]:{a[True]} \na[False]:{a[False]}')


[1, 2, 3, 4, 5, 6]
a[0]:1 
a[1]:2 
a[2]:3 
a[3]:4 
a[4]:5 
a[5]:6 
a[-1]:6 
a[-2]:5 
a[True]:2 
a[False]:1


#### 슬라이싱 slicing
a[start:end + 1:step]

In [4]:
#### 슬라이싱 slicing
a = [1,2,3,4,5,6]
print(f'a[0:1]  :  {a[0:1]}                   from index 0 to index 2')  
print(f'a[:3]   :  {a[:3]}             시작 인덱스 생략가능')   
print(f'a[2:5]  :  {a[2:5]}             from index 2 to index 4')   
print(f'a[2:]   :  {a[2:]}          끝 인덱스 생략가능')  
print(f'a[:]    :  {a[:]}    print(a) 와 동일')    
print(f'a[::3]  :  {a[::3]}                step을 3으로')  
print(f'a[::-1] :  {a[::-1]}    요소의 순서를 거꾸로 변경한다') 

a[0:1]  :  [1]                   from index 0 to index 2
a[:3]   :  [1, 2, 3]             시작 인덱스 생략가능
a[2:5]  :  [3, 4, 5]             from index 2 to index 4
a[2:]   :  [3, 4, 5, 6]          끝 인덱스 생략가능
a[:]    :  [1, 2, 3, 4, 5, 6]    print(a) 와 동일
a[::3]  :  [1, 4]                step을 3으로
a[::-1] :  [6, 5, 4, 3, 2, 1]    요소의 순서를 거꾸로 변경한다


In [5]:
import numpy as np
a = np.array([0,1,2,3,4,5])

### 넘파이(NumPy) : 배열(ndarray, n dimension array)
* 리스트(list) : Linked List구조(불연속), 동작 속도가 느리다, comma로 요소구별, 서로 다른 자료형 사용가능 
* 배열(ndarray) : 연속된 메모리 구조, 동작 속도가 빠르다, comma를 사용하지 않고 공백으로 요소 구별,오직 한 가지 타입만 갖을 수 있다 

#### np.arange(start,end+1,step)

In [6]:
#### np.arange(start,end+1,step)
a = np.arange(10)
b = np.arange(1, 12, 2)
print(f'a의 배열(ndarray) : {a}')
print(f'type of a : {type(a)} \n\n')
print(f'b의 배열(ndarray)(np.arange(1, 12, 2)) : {b}')

a의 배열(ndarray) : [0 1 2 3 4 5 6 7 8 9]
type of a : <class 'numpy.ndarray'> 


b의 배열(ndarray)(np.arange(1, 12, 2)) : [ 1  3  5  7  9 11]


### 차원(dimension, Rank) 과 Shape
* 차원(Dimension, Rank) : 1,2,3 차원 , n 차원, 첫 데이터까지의 대괄호의 갯수
* Shape : 차원의 요소의 수, 튜플 형식
##### 1차원 Shape : (x,)
##### 2차원 Shape : (x,y)  , 행렬(matrix)
##### 3차원 Shape : (x,y,z) , (면,행,열)
...
##### n차원 Shape : (x,y,z,....)

In [7]:
# 1차원의 배열의 Shape
a = np.arange(12)
print(a,type(a))
print(f'shape로 차원 확인 {a.shape} : 1차원')  # (12,)  ----> 1차원
t = a.shape
print(f'type of a.shape : {type(t)} ')
print((a.shape)[0]) # 1차원 안에 배열의 개수

[ 0  1  2  3  4  5  6  7  8  9 10 11] <class 'numpy.ndarray'>
shape로 차원 확인 (12,) : 1차원
type of a.shape : <class 'tuple'> 
12


In [8]:
# 2차원 배열의 Shape : 행(row,가로,수직,axis = 0) 과 열(column,세로,수평,axis =1)  ==> 필수 암기
m = np.array([[0,1,2],
              [0,1,2]])
print(m)
print(m.shape)   # (2,3)  --> 2차원 , 행렬(matrix)
print(m.shape[0], m.shape[1])

[[0 1 2]
 [0 1 2]]
(2, 3)
2 3


In [9]:
# 3차원 배열의 Shape : (면,행,열)
m = np.array([[[0,1,2],
               [3,4,5]],
              [[0,1,2],
               [3,4,5]]])
# print(f'{m}\n')

for i in range(int(m.shape[0])):
    print(f'{i+1}번째 면 : \n {m[i]} \n')

print(f'{m.shape} = (면, 행, 열)')  # (2,2,3) ---> 3차원
print(f'm.shape[0],m.shape[1],m.shape[2] = {m.shape[0],m.shape[1],m.shape[2]}')

1번째 면 : 
 [[0 1 2]
 [3 4 5]] 

2번째 면 : 
 [[0 1 2]
 [3 4 5]] 

(2, 2, 3) = (면, 행, 열)
m.shape[0],m.shape[1],m.shape[2] = (2, 2, 3)


### 배열의 shape 바꾸기 : reshape() 함수

In [10]:
# reshape로 행,열을 재배열하면 다음 행으로 넘어간다

m1 = np.arange(12) # 0~11 배열
m2 = m1.reshape(3,4)
m3 = m1.reshape(4,3)
m4 = m1.reshape(2,6)
m5 = m1.reshape(12,1)

print(f'(행,열)\n')
print(f'(12,) : \n m1={m1}\n shape = {m1.shape}\n')  # (12,)
print(f'(12,)->(3,4) : \n m2={m2}\n shape = {m2.shape}\n')  # (3, 4)
print(f'(12,)->(4,3) : \n m3={m3}\n shape = {m3.shape} \n')  # (4, 3)
print(f'(12,)->(2,6) : \n m4={m4}\n shape = {m4.shape} \n')  # (2, 6)
print(f'(12,)->(12,1) : \n m5={m5}\n shape = {m5.shape} \n')  # (12, 1)

(행,열)

(12,) : 
 m1=[ 0  1  2  3  4  5  6  7  8  9 10 11]
 shape = (12,)

(12,)->(3,4) : 
 m2=[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 shape = (3, 4)

(12,)->(4,3) : 
 m3=[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 shape = (4, 3) 

(12,)->(2,6) : 
 m4=[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
 shape = (2, 6) 

(12,)->(12,1) : 
 m5=[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
 shape = (12, 1) 



In [11]:
# 3차원 배열로 변환
m3 = m1.reshape(2,2,3)
print(m3,m3.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


##### 4차원 연습

In [12]:
# 4차원 배열로 변환
m4 = m1.reshape(3,2,1,2)
print(m4,m4.shape)

# 4차원 배열 첫번째 요소 출력해보기
for i in range(3):
    print(f'\n m4[{i}]=\n{m4[i]}')

[[[[ 0  1]]

  [[ 2  3]]]


 [[[ 4  5]]

  [[ 6  7]]]


 [[[ 8  9]]

  [[10 11]]]] (3, 2, 1, 2)

 m4[0]=
[[[0 1]]

 [[2 3]]]

 m4[1]=
[[[4 5]]

 [[6 7]]]

 m4[2]=
[[[ 8  9]]

 [[10 11]]]


In [13]:
print(f' m4[0]=\n{m4[0]}')
print(f'\n m4[0][0]=\n{m4[0][0]}')
print(f'\n m4[0][0][0]=\n{m4[0][0][0]}')
print(f'\n m4[0][0][0][0]=\n{m4[0][0][0][0]}')

print(f'\n type(m4[0][0][0])=\n{type(m4[0][0][0])}')
print(f'\n type(m4[0][0][0][0])=\n{type(m4[0][0][0][0])}')

 m4[0]=
[[[0 1]]

 [[2 3]]]

 m4[0][0]=
[[0 1]]

 m4[0][0][0]=
[0 1]

 m4[0][0][0][0]=
0

 type(m4[0][0][0])=
<class 'numpy.ndarray'>

 type(m4[0][0][0][0])=
<class 'numpy.int32'>


#### -1 을 사용한 reshape  : 요소수를 자동으로 계산

In [14]:
#### -1 을 사용한 reshape  : 요소수를 자동으로 계산
m1 = np.arange(12)
print(m1)
print(m1.shape)  # (12,)

print(f'\nreshape(-1,6)으로 -1의 부분인 행을 자동으로 계산한다 -> (2,6)')
m2 = m1.reshape(-1,6)  # 행의 요소수를 자동으로 계산(알아서 계산해서 만들어줌), 2
print(m2,m2.shape)

print(f'\nreshape(4,-1)으로 -1의 부분인 열을 자동으로 계산한다 -> (4,3)')
m2 = m1.reshape(4,-1)  # 열의 요소수를 자동으로 계산, 3
print(m2,m2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)

reshape(-1,6)으로 -1의 부분인 행을 자동으로 계산한다 -> (2,6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)

reshape(4,-1)으로 -1의 부분인 열을 자동으로 계산한다 -> (4,3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] (4, 3)


### 배열의 인덱싱과 슬라이싱

In [15]:
# 1차원 배열의 인덱싱과 슬라이싱 : list 와 동일한 방법
d = np.arange(12)
print(f'1차원 배열 : 리스트와 동일한 방법으로 인덱싱과 슬라이싱 가능하다')
print(d,d.shape)  # (12,)

# d[0],d[1],d[2],d[3],d[-1]
print(f'\nd[0]  : {d[0]}\nd[1]  : {d[1]}\nd[2]  : {d[2]}\nd[3]  : {d[3]}\nd[-1] : {d[-1]}')

# d[2:8],d[:],d[:-1]
print(f'\nd[2:8] : {d[2:8]}\nd[:]   : {d[:]}\nd[:-1] : {d[:-1]}')

# d[::2], d[::-1]
print(f'\n[start:end:step] , step=-1(reverse)')
print(f'd[::2]  : {d[::2]}\nd[::-1] : {d[::-1]}') # step을 -1로 하면 요소의 순서를 거꾸로 변경한다

print(f'\n리스트처럼 요소 변경 가능')
d[0] = 10   # list 처럼 요소 변경이 가능
print(f'd[0]=10 \nd = {d}')

1차원 배열 : 리스트와 동일한 방법으로 인덱싱과 슬라이싱 가능하다
[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)

d[0]  : 0
d[1]  : 1
d[2]  : 2
d[3]  : 3
d[-1] : 11

d[2:8] : [2 3 4 5 6 7]
d[:]   : [ 0  1  2  3  4  5  6  7  8  9 10 11]
d[:-1] : [ 0  1  2  3  4  5  6  7  8  9 10]

[start:end:step] , step=-1(reverse)
d[::2]  : [ 0  2  4  6  8 10]
d[::-1] : [11 10  9  8  7  6  5  4  3  2  1  0]

리스트처럼 요소 변경 가능
d[0]=10 
d = [10  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
# 2차원 배열의 인덱싱과 슬라이싱 
# data[행,열]
print(f'2차원 배열 인덱싱 슬라이싱')
d = np.arange(12).reshape(3,4)
print(f'2차원 배열 d = \n{d} \nd의 shape ={d.shape}')

# 인덱싱
print(f'\n인덱싱')
print(f'd[0][1] : {d[0][1]}') 
print(f'd[0,1]  : {d[0,1]}')   
print(f'd[2,1]  : {d[2,1]}')   

# 슬라이싱
print(f'\n슬라이싱')
print(f'd[0]   : {d[0]}')     # [0 1 2 3]
print(f'd[0,:] : {d[0,:]}')   # [0 1 2 3]

print(d[:,:-1])  # (3,3) , 마지막 열(컬럼)을 제외
print(d[:,1:])   # (3,3) , 첫번째 열(컬럼)을 제외
print(d[::2,::2])

d[0] = 20   # 0번 행의 모든 요소를 20으로 변경
print(d)

d[::2,::3] = 30    # 슬라이싱 된 요소 전체를 한번에 변경할 수 있다
print(d)

d[:,:] = -1        # 전체 요소를 한번에 변경할 수 있다
print(d)

2차원 배열 인덱싱 슬라이싱
2차원 배열 d = 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
d의 shape =(3, 4)

인덱싱
d[0][1] : 1
d[0,1]  : 1
d[2,1]  : 9

슬라이싱
d[0]   : [0 1 2 3]
d[0,:] : [0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 0  2]
 [ 8 10]]
[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[30 20 20 30]
 [ 4  5  6  7]
 [30  9 10 30]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


##### 3차원
[[[ 0  1  2]  
  [ 3  4  5]]  
  
 [[ 6  7  8]  
  [ 9 10 11]]]  
d[:,:-1,:-1] 의미 [전체, 마지막 열 제거, 마지막 열 제거]  
[[[0 1]]  
 [[6 7]]]   
d[:,-1,-1]   의미 [전체, 마지막, 마지막]  
[ 5 11]  
d[:,:,-1]    의미 [전체, 전체, 마지막]  
[[ 2  5]  
 [ 8 11]]  
d[:,1:,1:]   의미 [전체, 1번째부터, 1번째부터]  
[[[ 4  5]]  
  
 [[10 11]]]  

In [33]:
# 3차원 배열의 인덱싱과 슬라이싱
# data[면,행,열]
print('3차원 배열')
d = np.arange(12).reshape(2,2,3)
print(d,d.shape)

# 인덱싱
print('\n3차원 배열 인덱싱')
print('d[0][0][0] : ',d[0][0][0])  # 0 old style
print('d[0,0,0]   : ',d[0,0,0])    # 0
print('d[0,1,2]   : ',d[0,1,2])    # 5

# 슬라이싱
print('\n 3차원 배열 슬라이싱')
print('------------')
print(d[:,:-1,:-1])  # (2,1,2)
print('------------')
print(d[:,-1,-1])    # (2,)
print('------------')
print(d[:,:,-1])     # (2,2)
print('------------')
print(d[:,1:,1:])    # (2,1,2)
print('------------')

3차원 배열
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)

3차원 배열 인덱싱
d[0][0][0] :  0
d[0,0,0]   :  0
d[0,1,2]   :  5

 3차원 배열 슬라이싱
------------
[[[0 1]]

 [[6 7]]]
------------
[ 5 11]
------------
[[ 2  5]
 [ 8 11]]
------------
[[[ 4  5]]

 [[10 11]]]
------------


##### 인덱싱 슬라이싱 타입

In [34]:
# 인덱싱 결과는 scalar
# 슬라이싱 결과는 ndarray
a = np.arange(12)
print(a,a.shape)

print(a[0])    # 0, scalar
print(a[0:1])  # [0] , 배열(ndarray)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0
[0]


### 불린 인덱싱 : 조건식을 사용한 인덱싱, 조건 검색 필터를 사용한 추출(매우 중요)

In [47]:
a = np.array([1,2,3,4,5,6])
print('a : ',a)

print('\na > 2    : ',a > 2)
print('a[a > 2] : ',a[a > 2]) # 배열 a에서 2보다 큰 요소를 추출, 결과는 배열
# print(a[[False, False,  True,  True,  True,  True]])

boolean_index = np.array([True,False,True,False,True,True])
print('\nboolean_index     : ',boolean_index)
print('a[boolean_index]  : ',a[boolean_index])

print('\na[a!=3]              : ',a[a!=3])             # 배열 a에서 3이 아닌 요소를 추출
print('a[(a > 2) & (a < 6)] : ',a[(a > 2) & (a < 6)])  # 배열 a에서 2보다 크고 6보다 작은 요소를 추출
print('a[a % 2 == 0]        : ',a[a % 2 == 0])         # 2의 배수(짝수)를 추출
print('a[a < a.mean()]      : ',a[a < a.mean()])       # 평균보다 작은 값을 추출

a :  [1 2 3 4 5 6]

a > 2    :  [False False  True  True  True  True]
a[a > 2] :  [3 4 5 6]

boolean_index     :  [ True False  True False  True  True]
a[boolean_index]  :  [1 3 5 6]

a[a!=3]              :  [1 2 4 5 6]
a[(a > 2) & (a < 6)] :  [3 4 5]
a[a % 2 == 0]        :  [2 4 6]
a[a < a.mean()]      :  [1 2 3]


In [67]:
# 배열의 형상 다루기 : reshape(), flatten()(편평화),transpose()(전치)

# flatten() : 다차원 배열을 1차원으로 만든다
a = np.arange(12).reshape(3,4)
print('a : \n',a,a.shape)

f = a.flatten()      # (3,4)  ----> (12,)
print('\na.flatten = f : \n',f,f.shape)

# 데이터 순서를 거꾸로 변경
print('\n데이터의 순서를 거꾸로')
print('a[::-1]      \n',a[::-1])       # 행의 순서를 거꾸로 변경
print('a[:,::-1]   \n',a[:,::-1])     # 열의 순서를 거꾸로 변경
print('a[::-1,::-1] \n',a[::-1,::-1])  # 행과 열의 순서를 거꾸로 변경
print('-'*20)


a : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)

a.flatten = f : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)

데이터의 순서를 거꾸로
a[::-1]      
 [[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
a[:,::-1]   
 [[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
a[::-1,::-1] 
 [[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
--------------------


In [73]:
a = np.arange(12).reshape(3,4)
# transpose() : 전치 행렬 , 행과 열을 서로 맞바꾸는 함수
print('a\n',a)
print('-'*20)
print('t= a.transpose')
t = a.transpose()
print('-'*20)
print('t : \n',t)    # (3,4)  ---> (4,3)   , (x,y) --> (y,x)
print('-'*20)
print(t.shape)
print('-'*20)
print('a.T : \n',a.T)          # transpose()함수와 동일한 결과
print('-'*20)


# 임시로 1차원으로 변경하여 데우터를 채우고 다시 원래의 shape을 갖는다
# 배열의 요소 전체를 한번에 초기화 할때 사용
a.flat = 0
print(a)

a
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
t= a.transpose
--------------------
t : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
--------------------
(4, 3)
--------------------
a.T : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
--------------------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
